package domain

import (
	"strings"
	"time"
)

// The herd.
//
// A dairy knows its animals by the number on the yellow tag in their ear.
// That tag is the name, the record and the thing shouted across a shed,
// so it is the identifier here too — unique within a business, and never
// generated by this app, because it is written on a physical animal that
// existed before any of this.
//
// Everything else is optional. A farm entering thirty buffaloes on a
// Tuesday evening knows the tags; it may not know a birthdate for the
// ones it bought, and refusing the record until it does would mean the
// register never gets started. See Docs/DESIGN.md — the screen is a
// list, not a form to be completed.
type Animal struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
	// Tag is the ear-tag number. Compared with TagKey, so "A-12" and
	// "a12" are recognised as the same animal being entered twice.
	Tag  string `json:"tag"`
	Name string `json:"name"`
	// Species is "buffalo" or "cow". Kept apart from breed because the
	// two carry different gestation lengths, and a due date that is a
	// month out is worse than none.
	Species string `json:"species"`
	Breed   string `json:"breed"`
	Sex     string `json:"sex"`
	// BornOn and ArrivedOn are YYYY-MM-DD, either possibly empty. An
	// empty ArrivedOn means born on this farm — which is a fact, not a
	// gap, and is why the two are separate fields.
	BornOn    string `json:"born_on"`
	ArrivedOn string `json:"arrived_on"`
	Source    string `json:"source"`
	// Stage is where the animal is in its life: calf, heifer, milking,
	// dry, bull, sold, died. Set by the farmer rather than worked out
	// from dates — a buffalo is dried off when the farmer says so, and
	// an app that guessed would be wrong in front of somebody who knows.
	Stage  string `json:"stage"`
	Notes  string `json:"notes"`
	Active bool   `json:"active"`
}

// Stages an animal can be in. "sold" and "died" are here rather than
// being a deletion: an animal that left is a fact about the herd's
// history, and its milk records still happened.
const (
	StageCalf    = "calf"
	StageHeifer  = "heifer"
	StageMilking = "milking"
	StageDry     = "dry"
	StageBull    = "bull"
	StageSold    = "sold"
	StageDied    = "died"
)

var animalStages = map[string]bool{
	StageCalf: true, StageHeifer: true, StageMilking: true,
	StageDry: true, StageBull: true, StageSold: true, StageDied: true,
}

// ValidStage keeps the set closed. A stage the screens do not know how
// to draw would silently drop an animal out of every count on the page.
func ValidStage(stage string) bool { return animalStages[strings.ToLower(strings.TrimSpace(stage))] }

// Half these stages are facts about a female animal.
//
// A bull is never milking, dry or a heifer, and a cow is never a bull —
// these are not preferences a farm can hold differently, they are what
// the words mean. Offering "milking" for a male is how a herd ends up
// with a bull carrying a lactation record, which then quietly joins
// every total on the milking sheet.
//
// Calf, sold and died are common to both: the first is a young animal of
// either sex, and the last two are ways of leaving rather than stages of
// life.
var (
	femaleStages = []string{StageCalf, StageHeifer, StageMilking, StageDry, StageSold, StageDied}
	maleStages   = []string{StageCalf, StageBull, StageSold, StageDied}
)

// StagesFor lists the stages an animal of this sex can be in. Anything
// not "male" is treated as female, matching the field's own default —
// an animal whose sex was never recorded is far more likely to be a cow
// on a dairy than a bull.
func StagesFor(sex string) []string {
	if strings.EqualFold(strings.TrimSpace(sex), "male") {
		return maleStages
	}
	return femaleStages
}

// StageAllowedForSex reports whether an animal of this sex can be in this
// stage.
func StageAllowedForSex(stage, sex string) bool {
	stage = strings.ToLower(strings.TrimSpace(stage))
	for _, allowed := range StagesFor(sex) {
		if allowed == stage {
			return true
		}
	}
	return false
}

// DefaultStageFor is where an animal starts when nobody said. A dairy
// adding females is adding milking animals; a male defaults to calf
// rather than bull, because most males born on a dairy are calves and
// promoting one is a deliberate act.
func DefaultStageFor(sex string) string {
	if strings.EqualFold(strings.TrimSpace(sex), "male") {
		return StageCalf
	}
	return StageMilking
}

// Lactates reports whether this animal can have milk recorded against
// it at all. Milk from a male is not a data-entry mistake worth
// tolerating — it is impossible, and letting it through corrupts every
// total on the day it is entered.
func (a Animal) Lactates() bool {
	return !strings.EqualFold(strings.TrimSpace(a.Sex), "male")
}

// OnTheFarm is whether this animal is still part of the herd. Sold and
// died animals keep their records and leave the counts.
func (a Animal) OnTheFarm() bool {
	return a.Active && a.Stage != StageSold && a.Stage != StageDied
}

// TagKey is how two tags are compared: case and punctuation removed, so
// "A-12", "a 12" and "A12" are one animal. Farms write the same tag
// three ways across a year of notebooks.
func TagKey(tag string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(tag) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// Species, and what each one's gestation costs in days.
const (
	SpeciesBuffalo = "buffalo"
	SpeciesCow     = "cow"

	// A buffalo carries about ten and a half months, a cow about nine
	// and a half. Rounded to the usual herd-book figures rather than to
	// anything cleverer: a due date is a week somebody watches, not a
	// timestamp.
	buffaloGestationDays = 310
	cowGestationDays     = 283
)

func GestationDays(species string) int {
	if strings.EqualFold(strings.TrimSpace(species), SpeciesCow) {
		return cowGestationDays
	}
	return buffaloGestationDays
}

// One crossing and what came of it.
//
// This is the record a dairy actually keeps in a notebook: the day an
// animal was served, by which bull or which straw, whether the check
// came back in calf, and the day the calf arrived. It is a log rather
// than a field on the animal because an animal is served many times over
// its life, and last year's crossing is how anybody works out whether
// this one is late.
type Breeding struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
	AnimalID   string `json:"animal_id"`
	// CrossedOn is the day of service, and the day every date below is
	// counted from.
	CrossedOn string `json:"crossed_on"`
	// Method is "ai" or "natural".
	Method string `json:"method"`
	// Sire is the bull's tag, or the semen batch written on the straw.
	Sire string `json:"sire"`
	// Result: pending, pregnant, empty, aborted, calved.
	Result    string `json:"result"`
	CheckedOn string `json:"checked_on"`
	CalvedOn  string `json:"calved_on"`
	// CalfID links to the calf's own record once it has a tag of its
	// own, which turns a pile of crossings into a lineage.
	CalfID string `json:"calf_id"`
	Notes  string `json:"notes"`
}

const (
	BreedingPending  = "pending"
	BreedingPregnant = "pregnant"
	BreedingEmpty    = "empty"
	BreedingAborted  = "aborted"
	BreedingCalved   = "calved"
)

var breedingResults = map[string]bool{
	BreedingPending: true, BreedingPregnant: true, BreedingEmpty: true,
	BreedingAborted: true, BreedingCalved: true,
}

func ValidBreedingResult(result string) bool {
	return breedingResults[strings.ToLower(strings.TrimSpace(result))]
}

// DueOn is when a calf would be expected from this crossing, or "" when
// there is nothing to expect: a crossing that came back empty, aborted,
// or has already produced a calf is not a due date any more.
func (b Breeding) DueOn(species string) string {
	if b.Result != BreedingPending && b.Result != BreedingPregnant {
		return ""
	}
	served, err := time.Parse(DateLayout, b.CrossedOn)
	if err != nil {
		return ""
	}
	return served.AddDate(0, 0, GestationDays(species)).Format(DateLayout)
}

// What one animal gave on one day.
//
// Morning and evening are separate because that is how it is measured —
// twice, into a can, by whoever milked — and a single daily figure would
// be somebody adding two numbers in their head before typing one. Both
// default to nothing, and nothing means no record rather than zero: a
// cow that gave nothing is a fact worth entering, and a day nobody
// wrote down is not the same fact.
type MilkYield struct {
	BusinessID string  `json:"business_id"`
	AnimalID   string  `json:"animal_id"`
	Date       string  `json:"date"`
	Morning    float64 `json:"morning"`
	Evening    float64 `json:"evening"`
}

func (m MilkYield) Total() float64 { return m.Morning + m.Evening }

// Something done to an animal on a day: a jab, a drench, a treatment, a
// vet's visit.
//
// One log rather than a table per kind, because they are the same record
// with different words on it — a date, what was given, by whom, what it
// cost, and when the next one is due. Kind is what the screens sort by.
//
// Two fields carry the weight and are worth reading twice:
//
//   - NextDueOn turns a log into a schedule. FMD is every six months in
//     India, HS and BQ annually; nobody remembers that per animal across
//     forty of them, and a vaccination missed is the whole point of
//     keeping the book.
//   - MilkWithheldUntil is a safety interlock. Milk from a treated
//     animal must not reach the churn — withdrawal is three days for
//     oxytetracycline, six for ciprofloxacin, seventy-two to ninety-six
//     hours for most intramammary mastitis tubes. Getting this wrong
//     contaminates a whole collection, not one animal's can.
type HealthEvent struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
	AnimalID   string `json:"animal_id"`
	// Kind is vaccination, deworming, treatment or checkup.
	Kind string `json:"kind"`
	// What was given or found: "FMD", "Ivermectin", "mastitis".
	Name string `json:"name"`
	Date string `json:"date"`
	// Batch and Dose matter for a vaccine and are why a vaccination
	// record exists at all in an audit — see the cold-chain guidance any
	// dairy board publishes.
	Batch string `json:"batch"`
	Dose  string `json:"dose"`
	Vet   string `json:"vet"`
	// CostRupees is whole rupees. A dairy counting paise on a vet bill
	// is not a thing anybody asked for.
	CostRupees        int    `json:"cost_rupees"`
	NextDueOn         string `json:"next_due_on"`
	MilkWithheldUntil string `json:"milk_withheld_until"`
	Notes             string `json:"notes"`
}

const (
	HealthVaccination = "vaccination"
	HealthDeworming   = "deworming"
	HealthTreatment   = "treatment"
	HealthCheckup     = "checkup"
)

var healthKinds = map[string]bool{
	HealthVaccination: true, HealthDeworming: true,
	HealthTreatment: true, HealthCheckup: true,
}

func ValidHealthKind(kind string) bool {
	return healthKinds[strings.ToLower(strings.TrimSpace(kind))]
}

// How long until the same thing is due again, for the jabs an Indian
// dairy actually gives.
//
// Defaults, not rules: a business can type any next-due date it likes,
// and a vet who says otherwise wins. They exist so that recording "FMD"
// does not also mean doing arithmetic on a phone in a shed. Brucellosis
// is absent on purpose — it is given once in a female calf's life, so
// there is no next one to schedule.
var vaccineIntervalDays = map[string]int{
	"fmd":           182,
	"hs":            365,
	"bq":            365,
	"hs-bq":         365,
	"theileria":     365,
	"deworming":     182,
	"anthrax":       365,
	"black quarter": 365,
}

// SuggestedNextDue is when a jab of this name would normally come round
// again, or "" when it is a one-off or unknown.
func SuggestedNextDue(name, on string) string {
	days, known := vaccineIntervalDays[strings.ToLower(strings.TrimSpace(name))]
	if !known {
		return ""
	}
	given, err := time.Parse(DateLayout, on)
	if err != nil {
		return ""
	}
	return given.AddDate(0, 0, days).Format(DateLayout)
}

// WithholdingOn reports whether this event still bars the animal's milk
// on the given date. The last day is inclusive: "withheld until the
// 12th" is milk you throw away on the 12th.
func (h HealthEvent) WithholdingOn(date string) bool {
	return h.MilkWithheldUntil != "" && date <= h.MilkWithheldUntil
}

// A warning raised about an animal, not a diagnosis.
//
// The one built-in kind is a milk yield falling against the animal's own
// recent average — the earliest sign a farmer normally works from ("she's
// usually ten litres, today it's seven"). Kind is a string rather than a
// closed set: an overdue vaccination or a missed heat is the same shape
// of fact — something worth a farmer's attention, raised once, cleared
// once dealt with — and should slot in later without a schema change.
//
// This app does not know *why* a yield dropped: heat stress, mastitis, a
// missed feed, coming into heat, or nothing at all. Note is where that
// knowledge lives, in the farmer's own words, once they have worked out
// what happened — the same trade this app already made with Animal.Notes
// and Breeding.Notes rather than a fixed taxonomy it would get wrong.
type HerdAlert struct {
	ID         string  `json:"id"`
	BusinessID string  `json:"business_id"`
	AnimalID   string  `json:"animal_id"`
	Kind       string  `json:"kind"`
	RaisedOn   string  `json:"raised_on"`
	Baseline   float64 `json:"baseline"`
	Actual     float64 `json:"actual"`
	Status     string  `json:"status"`
	Note       string  `json:"note"`
	ResolvedOn string  `json:"resolved_on"`
}

const (
	AlertYieldDrop = "yield_drop"
	// AlertManual is one a farmer raised themselves — "watch this one,
	// she was off her feed". The app cannot detect everything somebody
	// standing in the shed can see, and the honest answer to that is a
	// way to write it down rather than a cleverer detector.
	AlertManual = "manual"

	AlertOpen         = "open"
	AlertAcknowledged = "acknowledged"
	AlertResolved     = "resolved"
)

var alertKinds = map[string]bool{AlertYieldDrop: true, AlertManual: true}

func ValidAlertKind(kind string) bool {
	return alertKinds[strings.ToLower(strings.TrimSpace(kind))]
}

var alertStatuses = map[string]bool{
	AlertOpen: true, AlertAcknowledged: true, AlertResolved: true,
}

// ValidAlertStatus keeps the set closed, same reasoning as ValidStage.
func ValidAlertStatus(status string) bool {
	return alertStatuses[strings.ToLower(strings.TrimSpace(status))]
}

// DropPct is how far Actual fell below Baseline, as the number a farmer
// actually reads ("down 30%") rather than the two litres it takes to
// compute it.
func (a HerdAlert) DropPct() float64 {
	if a.Baseline <= 0 {
		return 0
	}
	return (a.Baseline - a.Actual) / a.Baseline * 100
}

// Yield-drop detection: how far back a baseline looks, how many of those
// days need an actual record before the baseline is trusted, and how far
// below it counts as a drop worth raising.
const (
	YieldAlertWindowDays = 14
	YieldAlertMinDays    = 5
	YieldAlertThreshold  = 0.20
)

// YieldBaseline is the trailing average of an animal's own recent days,
// counting only days that were actually recorded — a day nobody milked
// and wrote down is not a zero, and must not drag the average toward
// one, same reasoning as MilkYield's own doc comment. ok is false until
// there are enough recorded days to trust the number: a freshly-calved
// animal's first low day is not a drop, it is the only data point there
// is yet.
func YieldBaseline(recent []MilkYield) (baseline float64, ok bool) {
	if len(recent) < YieldAlertMinDays {
		return 0, false
	}
	sum := 0.0
	for _, y := range recent {
		sum += y.Total()
	}
	return sum / float64(len(recent)), true
}

// IsYieldDrop reports whether actual is far enough below baseline to be
// worth a farmer's attention. Everything past the threshold is the
// farmer's own judgement, recorded in the alert's Note once they have
// looked at the animal.
//
// threshold is a fraction; zero or nonsense falls back to the default,
// so a business that never set one behaves as it always did.
func IsYieldDrop(baseline, actual, threshold float64) bool {
	if threshold <= 0 || threshold >= 1 {
		threshold = YieldAlertThreshold
	}
	return baseline > 0 && actual < baseline*(1-threshold)
}
