package domain

import (
	"strings"
	"time"
)

// The herd.
//
// A dairy knows its animals by the number on the yellow tag in their ear.
// That tag is the name, the record and the thing shouted across a shed,
// so it is the identifier here too — unique within a business, and never
// generated by this app, because it is written on a physical animal that
// existed before any of this.
//
// Everything else is optional. A farm entering thirty buffaloes on a
// Tuesday evening knows the tags; it may not know a birthdate for the
// ones it bought, and refusing the record until it does would mean the
// register never gets started. See Docs/DESIGN.md — the screen is a
// list, not a form to be completed.
type Animal struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
	// Tag is the ear-tag number. Compared with TagKey, so "A-12" and
	// "a12" are recognised as the same animal being entered twice.
	Tag  string `json:"tag"`
	Name string `json:"name"`
	// Species is "buffalo" or "cow". Kept apart from breed because the
	// two carry different gestation lengths, and a due date that is a
	// month out is worse than none.
	Species string `json:"species"`
	Breed   string `json:"breed"`
	Sex     string `json:"sex"`
	// BornOn and ArrivedOn are YYYY-MM-DD, either possibly empty. An
	// empty ArrivedOn means born on this farm — which is a fact, not a
	// gap, and is why the two are separate fields.
	BornOn    string `json:"born_on"`
	ArrivedOn string `json:"arrived_on"`
	Source    string `json:"source"`
	// Stage is where the animal is in its life: calf, heifer, milking,
	// dry, bull, sold, died. Set by the farmer rather than worked out
	// from dates — a buffalo is dried off when the farmer says so, and
	// an app that guessed would be wrong in front of somebody who knows.
	Stage  string `json:"stage"`
	Notes  string `json:"notes"`
	Active bool   `json:"active"`
}

// Stages an animal can be in. "sold" and "died" are here rather than
// being a deletion: an animal that left is a fact about the herd's
// history, and its milk records still happened.
const (
	StageCalf    = "calf"
	StageHeifer  = "heifer"
	StageMilking = "milking"
	StageDry     = "dry"
	StageBull    = "bull"
	StageSold    = "sold"
	StageDied    = "died"
)

var animalStages = map[string]bool{
	StageCalf: true, StageHeifer: true, StageMilking: true,
	StageDry: true, StageBull: true, StageSold: true, StageDied: true,
}

// ValidStage keeps the set closed. A stage the screens do not know how
// to draw would silently drop an animal out of every count on the page.
func ValidStage(stage string) bool { return animalStages[strings.ToLower(strings.TrimSpace(stage))] }

// OnTheFarm is whether this animal is still part of the herd. Sold and
// died animals keep their records and leave the counts.
func (a Animal) OnTheFarm() bool {
	return a.Active && a.Stage != StageSold && a.Stage != StageDied
}

// TagKey is how two tags are compared: case and punctuation removed, so
// "A-12", "a 12" and "A12" are one animal. Farms write the same tag
// three ways across a year of notebooks.
func TagKey(tag string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(tag) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// Species, and what each one's gestation costs in days.
const (
	SpeciesBuffalo = "buffalo"
	SpeciesCow     = "cow"

	// A buffalo carries about ten and a half months, a cow about nine
	// and a half. Rounded to the usual herd-book figures rather than to
	// anything cleverer: a due date is a week somebody watches, not a
	// timestamp.
	buffaloGestationDays = 310
	cowGestationDays     = 283
)

func GestationDays(species string) int {
	if strings.EqualFold(strings.TrimSpace(species), SpeciesCow) {
		return cowGestationDays
	}
	return buffaloGestationDays
}

// One crossing and what came of it.
//
// This is the record a dairy actually keeps in a notebook: the day an
// animal was served, by which bull or which straw, whether the check
// came back in calf, and the day the calf arrived. It is a log rather
// than a field on the animal because an animal is served many times over
// its life, and last year's crossing is how anybody works out whether
// this one is late.
type Breeding struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
	AnimalID   string `json:"animal_id"`
	// CrossedOn is the day of service, and the day every date below is
	// counted from.
	CrossedOn string `json:"crossed_on"`
	// Method is "ai" or "natural".
	Method string `json:"method"`
	// Sire is the bull's tag, or the semen batch written on the straw.
	Sire string `json:"sire"`
	// Result: pending, pregnant, empty, aborted, calved.
	Result    string `json:"result"`
	CheckedOn string `json:"checked_on"`
	CalvedOn  string `json:"calved_on"`
	// CalfID links to the calf's own record once it has a tag of its
	// own, which turns a pile of crossings into a lineage.
	CalfID string `json:"calf_id"`
	Notes  string `json:"notes"`
}

const (
	BreedingPending  = "pending"
	BreedingPregnant = "pregnant"
	BreedingEmpty    = "empty"
	BreedingAborted  = "aborted"
	BreedingCalved   = "calved"
)

var breedingResults = map[string]bool{
	BreedingPending: true, BreedingPregnant: true, BreedingEmpty: true,
	BreedingAborted: true, BreedingCalved: true,
}

func ValidBreedingResult(result string) bool {
	return breedingResults[strings.ToLower(strings.TrimSpace(result))]
}

// DueOn is when a calf would be expected from this crossing, or "" when
// there is nothing to expect: a crossing that came back empty, aborted,
// or has already produced a calf is not a due date any more.
func (b Breeding) DueOn(species string) string {
	if b.Result != BreedingPending && b.Result != BreedingPregnant {
		return ""
	}
	served, err := time.Parse(DateLayout, b.CrossedOn)
	if err != nil {
		return ""
	}
	return served.AddDate(0, 0, GestationDays(species)).Format(DateLayout)
}

// What one animal gave on one day.
//
// Morning and evening are separate because that is how it is measured —
// twice, into a can, by whoever milked — and a single daily figure would
// be somebody adding two numbers in their head before typing one. Both
// default to nothing, and nothing means no record rather than zero: a
// cow that gave nothing is a fact worth entering, and a day nobody
// wrote down is not the same fact.
type MilkYield struct {
	BusinessID string  `json:"business_id"`
	AnimalID   string  `json:"animal_id"`
	Date       string  `json:"date"`
	Morning    float64 `json:"morning"`
	Evening    float64 `json:"evening"`
}

func (m MilkYield) Total() float64 { return m.Morning + m.Evening }
